version: '3.8'

services:

  app:
    container_name: app
    build: 
      context: ./app
      dockerfile: Dockerfile
    restart: always
    ports:
        - 4000:3000
    volumes:
      - ./shared:/shared
      - ./app:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    networks:
      - rosid_link

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile 

    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./shared:/shared
      - ./server:/server
      - /server/node_modules
    env_file:
      - ./server/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    networks:
      - rosid_link 
    depends_on:
      - database
    
  database:
    container_name: database
    image: mongo:7.0.7-jammy
    restart: always
    env_file:
      - ./server/.env
    ports:
      - 37017:27017
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    networks:
      - rosid_link

networks:
  rosid_link:
    driver: bridge
