version: '3.8'

services:

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile 

    restart: always
    ports:
      - "3000:3000"
    networks:
      - rosid_link 
    depends_on:
      - database
    
  database:
    container_name: database
    image: mongo:$MONGODB_VERSION
    restart: always
    env_file:
      - .env
    ports:
      - 27017:$MONGODB_PORT
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    networks:
      - rosid_link

networks:
  rosid_link:
    driver: bridge
