import { Receipt } from "../types";

export function getReceiptExample(): Receipt {
  return {
    vendor: "Lisburn Rd Superstore",
    subtotal: 28.44,
    savings: 0.5,
    total: 27.94,
    currency: "GBP",
    items: [
      {
        label: "Tesco Chicken Breast Fillet",
        price: 11,
        quantity: 2,
        category: "Meat",
        expirable: false,
        subtotal: 22,
        savings: 0,
      },
      {
        label: "Hearty Food Thin Pepperoni Pizza",
        price: 0.97,
        quantity: 1,
        category: "Frozen Food",
        expirable: true,
        subtotal: 0.97,
        savings: 0,
      },
      {
        label: "Hygex 290mm X 30m Kitchen Foil",
        price: 3.5,
        quantity: 1,
        category: "Household",
        expirable: false,
        subtotal: 3.5,
        savings: 0.5,
      },
      {
        label: "Tesco Basmati Rice 1kg",
        price: 1.85,
        quantity: 1,
        category: "Grains",
        expirable: false,
        subtotal: 1.85,
        savings: 0,
      },
      {
        label: "Tesco Raspberries 150g",
        price: 1.8,
        quantity: 1,
        category: "Fruits",
        expirable: true,
        subtotal: 1.8,
        savings: 0,
      },
      {
        label: "Tesco Ni Whole Milk 1 Litre",
        price: 1.1,
        quantity: 1,
        category: "Dairy",
        expirable: true,
        subtotal: 1.1,
        savings: 0,
      },
      {
        label: "Skea Big 6 Eggs",
        price: 1.8,
        quantity: 1,
        category: "Dairy",
        expirable: true,
        subtotal: 1.8,
        savings: 0,
      },
      {
        label: "Wilson's Northern Ireland Baking Potatoes",
        price: 0,
        quantity: 1,
        category: "Vegetables",
        expirable: false,
        subtotal: 0,
        savings: 0,
      },
      {
        label: "Rosedene Farms Blueberries",
        price: 1.59,
        quantity: 1,
        category: "Fruits",
        expirable: true,
        subtotal: 1.59,
        savings: 0,
      },
      {
        label: "Tesco Garam Masala Spice Blend",
        price: 1,
        quantity: 1,
        category: "Seasoning",
        expirable: false,
        subtotal: 1,
        savings: 0,
      },
      {
        label: "Tesco Garlic & Ginger Paste",
        price: 1.8,
        quantity: 1,
        category: "Condiment",
        expirable: true,
        subtotal: 1.8,
        savings: 0,
      },
      {
        label: "Tesco Red Onions Loose",
        price: 1,
        quantity: 0.88,
        category: "Vegetables",
        expirable: false,
        subtotal: 0.88,
        savings: 0,
      },
    ],
  };
}
